name: Open Technologies
favicon: null
layout_spectrum: 0.53394
typography_spectrum: 0.49386
title: Open Technologies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#184399'
    - '#86a3cb'
    - '#6686bd'
    - '#dedeec'
  brandStrength: 0.30650168657302856
  lightness: 0.1956541957333684
  saturation: 0.6212472324259579
  rhythmicContrast: 0.12529758387245238
purpose: []
